/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab7;

public class Huffman {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Huffman().getGreeting());
    }
}
